# Excluded files
exclude:
- README.md
- LICENSE
- CNAME

# Gems
gems:
- jekyll-github-metadata
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jemoji

repository: "timoman7/timoman7.github.io"

jekyll-mentions: https://twitter.com

# SCSS
sass:
  style: :compressed

# Site info
url: https://timoman7.github.io
title: "CollegeRepo"
name: "Tim C"
description: "Stuff"
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=300"

twitter:
  username: SSJ3Bane

author:
  twitter: SSJ3Bane

seo:
  author: "Tim C"
